(parsecvs) avoid "git mktag" failure with newer git
With recent git, parsecvs now always fails like this:

  ...
  Save:                              master *....................     1 of   269
  Save:                              master *....................     2 of   269
  error: char77: malformed tagger field
  fatal: invalid tag signature file
  git-mktag < '.git-cvs/tag-0': No such file or directory

This is due to the change that makes git's mktag perform
stricter input validation.  parsecvs patch below.

[BTW, Keith, or anyone with write access to the parsecvs repo,
 I have a few other patches, but a few I sent have gone un-applied
 and with no response for months, I'm hoping there's a maintained
 repository somewhere else.

 I've been using this: git://people.freedesktop.org/~keithp/parsecvs

 Today's failure nearly pushed me to cvs2git (aka cvs2svn
 http://cvs2svn.tigris.org/cvs2git.html), which I hear is good,
 although still pretty new.  Since this fix was easy, I'm sticking
 with parsecvs for now. ]

>From 9c6ca141e82fae93ff173b87a27c118c5e87547c Mon Sep 17 00:00:00 2001
From: Jim Meyering <meyering@redhat.com>
Date: Wed, 9 Apr 2008 11:53:29 +0200
Subject: [PATCH] avoid "git mktag" failure with newer git

* git.c (git_mktag): Emit full tagger information, now that
git's mktag (since git's 5fbd0a44cfee7be96fe29b9252f34b8f1bce9ac5
on 2008-04-02) is more strict about it.

Signed-off-by: Jim Meyering <meyering@redhat.com>